#!/bin/sh /etc/rc.common
# Copyright (C) 2018 OpenWrt.org   

START=98

USE_PROCD=1

start_service() {
 　　procd_open_instance

 　　procd_set_param respawn

 　　procd_set_param command /usr/bin/packet_forwarder/start.sh

 　　procd_close_instance
}
